---
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: nitro-neo4j
    namespace: human-connection
  spec:
    replicas: 1
    strategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: "100%"
    selector:
      matchLabels:
        human-connection.org/selector: deployment-human-connection-neo4j
    template:
      metadata:
        annotations:
          backup.velero.io/backup-volumes: neo4j-data
        labels:
          human-connection.org/selector: deployment-human-connection-neo4j
        name: nitro-neo4j
      spec:
        containers:
        - name: nitro-neo4j
          image: humanconnection/neo4j:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1G"
            limits:
              memory: "2G"
          envFrom:
          - configMapRef:
              name: configmap
          ports:
          - containerPort: 7687
          - containerPort: 7474
          volumeMounts:
            - mountPath: /data/
              name: neo4j-data
        volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-data-claim
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
