apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    ocelot.social/commit: COMMIT
    ocelot.social/selector: deployment-ocelot-social-webapp
  name: web
  namespace: ocelot-social
spec:
  minReadySeconds: 15
  progressDeadlineSeconds: 60
  replicas: 2
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      ocelot.social/selector: deployment-ocelot-social-webapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        ocelot.social/commit: COMMIT
        ocelot.social/selector: deployment-ocelot-social-webapp
      name: web
    spec:
      containers:
      - env:
        - name: HOST
          value: 0.0.0.0
        envFrom:
        - configMapRef:
            name: configmap
        - secretRef:
            name: ocelot-social
        image: ocelotsocialnetwork/webapp:latest
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
