apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    ocelot.social/commit: COMMIT
    ocelot.social/selector: deployment-human-connection-backend
  name: backend
  namespace: ocelot-social
spec:
  minReadySeconds: 15
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      ocelot.social/selector: deployment-human-connection-backend
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: uploads
      creationTimestamp: null
      labels:
        ocelot.social/commit: COMMIT
        ocelot.social/selector: deployment-human-connection-backend
      name: backend
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: configmap
        - secretRef:
            name: ocelot-social
        image: ocelotsocialnetwork/develop-backend:latest
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 4000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /develop-backend/public/uploads
          name: uploads
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-claim
status: {}
