apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ocelot-social
  labels:
    ocelot.social/selector: deployment-ocelot-social-backend
spec:
  ports:
    - name: web
      port: 4000
      targetPort: 4000
  selector:
    ocelot.social/selector: deployment-ocelot-social-backend
