apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: ocelot-social
  labels:
    ocelot.social/selector: deployment-human-connection-web
spec:
  ports:
    - name: web
      port: 3000
      targetPort: 3000
  selector:
    ocelot.social/selector: deployment-human-connection-web
