apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: ocelot-social
  labels:
    ocelot.social/selector: deployment-human-connection-neo4j
spec:
  ports:
  - name: bolt
    port: 7687
    targetPort: 7687
  - name: web
    port: 7474
    targetPort: 7474
  selector:
    ocelot.social/selector: deployment-human-connection-neo4j
