apiVersion: v1
kind: Service
metadata:
  name: mailserver
  namespace: human-connection
  labels:
    human-connection.org/selector: deployment-human-connection-mailserver
spec:
  ports:
  - name: web
    port: 80
    targetPort: 80
  - name: smtp
    port: 25
    targetPort: 25
  selector:
    human-connection.org/selector: deployment-human-connection-mailserver
