version: "3.4"

services:
  ########################################################
  # WEBAPP ###############################################
  ########################################################
  webapp:
    image: ocelotsocialnetwork/webapp:test
    build:
      target: test
    environment:
      - NODE_ENV="test"

  ########################################################
  # BACKEND ##############################################
  ########################################################
  backend:
    image: ocelotsocialnetwork/backend:test
    build:
      target: test
    environment:
      - NODE_ENV="test"
      - JWT_SECRET="b/&&7b78BF&fv/Vd"
      - MAPBOX_TOKEN="pk.eyJ1IjoiYnVzZmFrdG9yIiwiYSI6ImNraDNiM3JxcDBhaWQydG1uczhpZWtpOW4ifQ.7TNRTO-o9aK1Y6MyW_Nd4g"
      - PRIVATE_KEY_PASSPHRASE="a7dsf78sadg87ad87sfagsadg78"

  ########################################################
  # NEO4J ################################################
  ########################################################
  neo4j:
    image: ocelotsocialnetwork/neo4j:community
  
  ########################################################
  # MAINTENANCE ##########################################
  ########################################################
  maintenance:
    image: ocelotsocialnetwork/maintenance:test

  ########################################################
  # MAILSERVER TO FAKE SMTP ##############################
  ########################################################
  mailserver:
    image: djfarrelly/maildev
    ports:
      - 1080:80
    networks:
      - external-net
volumes:
  webapp_node_modules:
  backend_node_modules:
