version: "3.4"

services:
  webapp:
    environment:
      - "CI=${CI}"
    image: ocelotsocialnetwork/develop-webapp:build-and-test
    build:
      context: webapp
      target: build-and-test
  backend:
    environment:
      - "CI=${CI}"
    image: ocelotsocialnetwork/nitro-backend:build-and-test
    build:
      context: backend
      target: build-and-test
