version: "3.4"

services:
  webapp:
    build:
      context: webapp
      target: production
      args:
        - "BUILD_COMMIT=${TRAVIS_COMMIT}"
  backend:
    image: ocelotsocialnetwork/backend:latest
    build:
      context: ./backend
      target: production
      args:
        - "BUILD_COMMIT=${TRAVIS_COMMIT}"
  neo4j:
    build:
      context: neo4j
      args:
        - "BUILD_COMMIT=${TRAVIS_COMMIT}"
