version: "3.4"

services:
  webapp:
    image: ocelotsocialnetwork/webapp:development
    build:
      target: development
    environment:
      - NODE_ENV="development"
      # - DEBUG=true
      # - NUXT_BUILD=/tmp/nuxt # avoid file permission issues when `rm -rf .nuxt/`
    command: yarn run dev
    volumes:
      # This makes sure the docker container has its own node modules.
      # Therefore it is possible to have a different node version on the host machine
      - webapp_node_modules:/app/node_modules
      # bind the local folder to the docker to allow live reload
      - ./webapp:/app
  backend:
    image: ocelotsocialnetwork/develop-backend:development
    build:
      target: development
    environment:
      - NODE_ENV="development"
      - DEBUG=true
    volumes:
      # This makes sure the docker container has its own node modules.
      # Therefore it is possible to have a different node version on the host machine
      - backend_node_modules:/app/node_modules
      # bind the local folder to the docker to allow live reload
      - ./backend:/app
  neo4j:
    ports:
      # Also expose the playground
      - 7474:7474
    networks:
      # So we can access the playground from our host machine
      - external-net
  maintenance:
    image: ocelotsocialnetwork/develop-maintenance:latest
    build:
      context: webapp
      dockerfile: Dockerfile.maintenance
    networks:
      - external-net
    ports:
      - 3503:80
  mailserver:
    image: djfarrelly/maildev
    ports:
      - 1080:80
    networks:
      - external-net
volumes:
  webapp_node_modules:
  backend_node_modules:
