apiVersion: v1
kind: Secret
data:
  # decomment following lines for S3 bucket to store our images
  # AWS_ACCESS_KEY_ID: ---toBeSet---
  # AWS_BUCKET: ocelot-social-uploads
  # AWS_ENDPOINT: fra1.digitaloceanspaces.com
  # AWS_REGION: fra1
  # AWS_SECRET_ACCESS_KEY: ---toBeSet---
  JWT_SECRET: "Yi8mJjdiNzhCRiZmdi9WZA=="
  PRIVATE_KEY_PASSPHRASE: "YTdkc2Y3OHNhZGc4N2FkODdzZmFnc2FkZzc4"
  MAPBOX_TOKEN: "pk.eyJ1IjoiYnVzZmFrdG9yIiwiYSI6ImNraDNiM3JxcDBhaWQydG1uczhpZWtpOW4ifQ.7TNRTO-o9aK1Y6MyW_Nd4g"
  NEO4J_USERNAME: ""
  NEO4J_PASSWORD: ""
  REDIS_DOMAIN: ---toBeSet(IP)---
  REDIS_PASSWORD: ---toBeSet---
  REDIS_PORT: "---toBeSet(Port)---"
  SMTP_HOST: "mail.ocelot.social"
  SMTP_PASSWORD: "---toBeSet---"
  SMTP_PORT: "25"
  SMTP_USERNAME: "---toBeSet---"
metadata:
  name: ocelot-social
  namespace: ocelot-social
