apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: ocelot-social
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # cert-manager.io/issuer: "letsencrypt-staging"  # in case using issuers instead of a cluster-issuers
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  rules:
  - host: develop-k8s.ocelot.social
    http:
      paths:
        - backend:
            serviceName: web
            servicePort: 3000
          path: /
  - host: mail.ocelot.social
    http:
      paths:
      - backend:
          serviceName: mailserver
          servicePort: 80
        path: /
  tls:
  - hosts:
    - develop-k8s.ocelot.social
    secretName: tls
