apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance
  namespace: ocelot-social
spec:
  selector:
    matchLabels:
      ocelot.social/selector: deployment-ocelot-social-maintenance
  template:
    metadata:
      labels:
        ocelot.social/commit: COMMIT
        ocelot.social/selector: deployment-ocelot-social-maintenance
      name: maintenance
    spec:
      containers:
        - name: web
          env:
            - name: HOST
              value: 0.0.0.0
          image: ocelotsocialnetwork/develop-maintenance:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
