apiVersion: v1
kind: Service
metadata:
  name: maintenance
  namespace: ocelot-social
  labels:
    ocelot.social/selector: deployment-human-connection-maintenance
spec:
  ports:
    - name: web
      port: 80
      targetPort: 80
  selector:
    ocelot.social/selector: deployment-human-connection-maintenance
