apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maintenance
  namespace: human-connection
spec:
  selector:
    matchLabels:
      human-connection.org/selector: deployment-human-connection-maintenance
  template:
    metadata:
      labels:
        human-connection.org/commit: COMMIT
        human-connection.org/selector: deployment-human-connection-maintenance
      name: maintenance
    spec:
      containers:
        - name: web
          env:
            - name: HOST
              value: 0.0.0.0
          image: humanconnection/maintenance:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
