name: CI

on: [push]

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check translation files
        run: |
          scripts/translations/sort.sh
          scripts/translations/missing-keys.sh

      ##########################################################################
      # NEO4J ##################################################################
      ##########################################################################
      - name: Neo4J | Build `community` image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: ocelotsocialnetwork/neo4j
          tags: latest
          path: neo4j/
          push: false
      
      ##########################################################################
      # BACKEND ################################################################
      ##########################################################################
      # TODO: We want to push this to dockerhub
      #- name: Build backend production image
      #  uses: docker/build-push-action@v1.1.0
      #  with:
      #    repository: ocelotsocialnetwork/backend
      #    tags: production
      #    target: production
      #    path: backend/
      #    push: false

      # Build Docker Image (build)
      - name: backend | Build `build` image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: ocelotsocialnetwork/backend
          tags: build
          target: build
          path: backend/
          push: false
      
      # Lint
      - name: backend | Lint
        run: docker run --rm ocelotsocialnetwork/backend:build yarn run lint

      # Unit Tests
      - name: backend | unit tests
        run: docker run --rm ocelotsocialnetwork/backend:build yarn run test
        env:
          MAPBOX_TOKEN: "123ABC"

      ##########################################################################
      # WEBAPP #################################################################
      ##########################################################################
      # TODO: We want to push this to dockerhub
      #- name: Build webapp production image
      #  uses: docker/build-push-action@v1.1.0
      #  with:
      #    repository: ocelotsocialnetwork/webapp
      #    tags: production
      #    target: production
      #    path: webapp/
      #    push: false

      # Build Docker Image (build)
      - name: webapp | Build `build` image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: ocelotsocialnetwork/webapp
          tags: build
          target: build
          path: webapp/
          push: false

      # Lint
      - name: webapp | Lint
        run: docker run --rm ocelotsocialnetwork/webapp:build yarn run lint

      # Unit Tests
      - name: webapp | unit tests
        run: docker run --rm ocelotsocialnetwork/webapp:build yarn run test

